In [ ]:
""" 
Plotly is a Python library for creating interactive, high-quality graphs and charts, 
while Cufflinks is a Python library that acts as a bridge between Plotly and Pandas DataFrames.

"""

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import plotly.express as px
from plotly.offline import iplot

In [5]:
tips = sns.load_dataset("tips")
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [9]:
tips["total_bill"].iplot()

AttributeError: 'Series' object has no attribute 'iplot'